<a href="https://colab.research.google.com/github/Davjot/Conversational-AI-Assignments/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignemnt 1

# Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result_array = arr[::-1]
print("The result array is : ", str(result_array))

The result array :  [5 4 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods 

1st method

In [2]:
import numpy as np

arr1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
final_array = arr1.flatten()
print("The final array is : ", str(final_array))

The final array is :  [1 2 3 2 4 5 1 2 3]


2nd method

In [3]:
import numpy as np

arr1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
final_array = arr1.ravel()
print("The final array is : ", str(final_array))

The final array is :  [1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:

 arr1 = np.array([[1, 2], [3, 4]]) 

 arr2 = np.array([[1, 2], [3, 4]])

In [4]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4]])

if np.array_equal(array1 , array2):
  print("Both the arrays are equal")
else:
  print("Both the arrays are not equal")

Both the arrays are equal


(d) Find the most frequent value and their indice(s) in the following arrays:

i. 
x = np.array([1,2,3,4,5,1,2,1,1,1])

In [5]:
import numpy as np

x = np.array([1,2,3,4,5,1,2,1,1,1])
count = np.bincount(x)
m = np.argmax(count)
print("The most frequented value is : ", m)
result = np.where(x == m)
print("Indices where most frequent value occur are : ", result)

The most frequented value is :  1
Indices where most frequent values occur are :  (array([0, 5, 7, 8, 9]),)


ii
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
count = np.bincount(y)
m = np.argmax(count)
print("The most frequented value is : ", m)
result = np.where(y == m )
print("Indices where most frequent value occur are : ", result)

The most frequented value is :  1
Indices where most frequent value occur are :  (array([0, 1, 2]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all the elements

In [7]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Original array : ")
print(gfg)

print("Sum of all elements is: ")
print(np.sum(gfg))

Original array : 
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements is: 
45


ii. Sum of all the elements row-wise

In [9]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Original array : ")
print(gfg)

print("Sum of all elements row-wise is: ")
print(np.sum(gfg, axis = 1))

Original array : 
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements row-wise is: 
[[14]
 [16]
 [15]]


iii. Sum of all the elements column-wise

In [10]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Original array : ")
print(gfg)

print("Sum of all elements column-wise is: ")
print(np.sum(gfg , axis = 0))

Original array : 
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements column-wise is: 
[[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

In [11]:
import numpy as np

n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag = np.diag(n_array)
print("Sum of diagonal elemnts is: ")
print(sum(diag))

Sum of diagonal elemnts is: 
176


ii, iii.Eigen values and Eigen vectors of matrix

In [17]:
import numpy as np

n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
w, v = np.linalg.eig(n_array)
print("Eigen values of the given matrix are: \n", w)
print("Eigen vectors of the given matrix are: \n", v)

Eigen values of the given matrix are: 
 [98.16835147 28.097044   49.73460452]
Eigen vectors of the given matrix are: 
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


iv.Inverse of matrix

In [18]:
import numpy as np

n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
y = np.linalg.inv(n_array)
print("Inverse of matrix is: \n",y)

Inverse of matrix is: 
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


v.Determinant of matrix

In [19]:
import numpy as np

n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
s = np.linalg.det(n_array)
print("Determinant of the matrix is: \n",y)

Determinant of the matrix is: 
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

 q = [[4, 5], [6, 7]]

In [21]:
import numpy as np

p = np.array([[1, 2] , [2, 3]])
q = np.array([[4, 5] , [6, 7]])
print("Multiplication of the matrices is: \n", np.dot(p, q))
print("Covariance of the matrices is: \n", np.cov(np.dot(p, q)))

Multiplication of the matrices is: 
 [[16 19]
 [26 31]]
Covariance of the matrices is: 
 [[ 4.5  7.5]
 [ 7.5 12.5]]


ii.p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]

In [22]:
import numpy as np

p = np.array([[1, 2] , [2, 3] , [4, 5]])
q = np.array([[4, 5 , 1] , [6, 7 , 2]])
print("Multiplication of the matrices is: \n", np.dot(p, q))
print("Covariance of the matrices is: \n", np.cov(np.dot(p, q)))

Multiplication of the matrices is: 
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance of the matrices is: 
 [[ 54.33333333  89.16666667 158.83333333]
 [ 89.16666667 146.33333333 260.66666667]
 [158.83333333 260.66666667 464.33333333]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [28]:
import numpy as np

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
#result = np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])

print("Inner product of the matrices is: \n", np.inner(x,y))
print("Outer product of the matrices is: \n", np.outer(x,y))
#print("Cartesian Product of the matrices is: \n", result)

Inner product of the matrices is: 
 [[17 52]
 [13 62]]
Outer product of the matrices is: 
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


# Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i.Find element-wise absolute value

ii.Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.

iii.Mean, Median and Standard Deviation of flattened array, of each column, and each row